version: 2.1
jobs:
  test:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
workflows:
  version: 2
  testing:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - development
